---
title: "Test graphs"
author: "Steve Simon"
date: "9/12/2019"
output: html_document
---

```{r load}
library(ggplot2)
```

```{r opacity}
x <- ((1:9)+0)/10
y <- rep(0, length=length(x))
g1 <- ggplot(data.frame(x, y), aes(x, y)) +
  geom_point(color="red", alpha=x, size=15) +
  expand_limits(y=c(-0.1, 2.1)) + 
  theme(
    panel.background = element_rect(fill = 'white'),
    panel.grid = element_line(color='white')) +
  scale_x_continuous(breaks=x, labels=paste0(100*x, "%")) +
  scale_y_continuous(breaks=NULL) +
  xlab(label="alpha") +
  ylab(label=" ")
g1
```

```{r}
g2 <- g1 +
  geom_segment(x=0, y=0.3, xend=1, yend=0.3, size=13) +
  geom_segment(x=0, y=0.5, xend=1, yend=0.5, size=13, color="green") +
  geom_point(y=y+0.4, color="red", alpha=x, size=15)
g2
```

```{r}
g3 <- g2 +
  geom_point(x=0.2, y=0.8, color="red", alpha=0.03, size=15) +
  geom_point(x=0.2, y=0.9, color="red", alpha=0.03, size=15) +
  geom_point(x=0.2, y=1.2, color="red", alpha=0.03, size=15) +
  geom_point(x=0.2, y=1.3, color="red", alpha=0.03, size=15) +
  geom_point(x=0.19, y=1.25, color="red", alpha=0.03, size=15) +
  geom_point(x=0.2, y=1.6, color="red", alpha=0.03, size=15) +
  geom_point(x=0.2, y=1.7, color="red", alpha=0.03, size=15) +
  geom_point(x=0.19, y=1.65, color="red", alpha=0.03, size=15) +
  geom_point(x=0.21, y=1.65, color="red", alpha=0.03, size=15)
g3
```