---
title: "Linegraphs, quiz"
author: "Steve Simon"
output: powerpoint_presentation
---

### Quick quiz (1 of 4)
Which Gestalt principles help the viewer to perceive objects as groups rather than individuals? (choose all that apply)

1. Similarity,
2. Proximity,
3. Connectedness,
4. Enclosure

<div class="notes">

Answer: All of the above

</div>

### Quick quiz (2 of 4)
Which aesthetics do lines have (choose the best answer)

1. Size
2. Shape
3. Color
4. All of the above
5. None of the above

<div class="notes">

Answer: 4 (all of the above)

</div>

### Quick quiz (3 of 4)
If you see an overlap of any size between two pairs of error bars, it means (choose the best answer)

1. the two means are statistically different
2. the two means are statistically the same
3. it depends

<div class="notes">

Answer: 3 (it depends)

</div>

### Quick quiz (4 of 4)
Labels work better than a legend for a graph because of the Gestalt principle of (choose the best answer)

1. similarity
2. connectedness
3. enclosure
4. proximity

<div class="notes">

Answer: 4 (proximity)

</div>
